name: Build JetBrains Plugin

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - closed
    branches:
      - 'main'
      - 'features/*'
      - 'release/*'

jobs:
  create-cherry-pick-issue:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true && startsWith(github.event.pull_request.base.ref, 'release') }}
    name: Create cherry-pick issue
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get latest release branch
        id: get_release_branch
        run: |
          LATEST_NUM_RELEASE=$(git branch -r | grep -Eo 'release/[0-9]+\.[0-9]+(\.[0-9]+)?' | sort -t/ -k2 -V | tail -n1)
          echo "latest_release=$LATEST_NUM_RELEASE" >> $GITHUB_OUTPUT

      - name: Create cherry-pick issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const currentTarget = context.payload.pull_request.base.ref;
            const prNumber = context.payload.pull_request.number;
            const prTitle = context.payload.pull_request.title;
            const prAuthor = context.payload.pull_request.user.login;

            let branchList = ['main'];
            const issueBody = `
              ### Cherry-pick Reminder

              @${prAuthor} Hello!
            
              This is an automatically created reminder. Your PR #${prNumber} (\`${prTitle}\`) is being merged into the \`${currentTarget}\` branch.
              
              Please ensure to cherry-pick these changes to the following branches:
              ${branchList}
            `

            try {
              const issue = await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `[Cherry-pick] PR #${prNumber} needs to be synchronized to other branches`,
                body: issueBody,
                labels: ['cherry-pick-hotfix'],
                assignees: [prAuthor] // Add PR author as assignee
              });

              console.log(`Created issue #${issue.data.number}`);
            } catch (error) {
              console.log('Error creating issue:', error);
              core.setFailed(error.message);
            }
